<!DOCTYPE html>

<?php
	require_once "connectdb.php";
	if(isset($_POST['submitted'])){
		$key = $_POST['key'];
		$query = "SELECT * from toi where data_id like '%$key%'";
		$result = $conn->query($query);
		if ($query ===FALSE) {
			die(mysql_error());		
		}
	}else{
		$query = "SELECT * from toi";
		$result = $conn->query($query);
	}
?>

<!-- <?php

$hostname = 'localhost';
$user = 'root';
$password = '';
$dbname = 'mydb';


$conn = new mysqli($hostname, $user, $password, $dbname);

$sql = "INSERT INTO toi (data_id, weight, heigh, age) VALUES ('as123', '12', '13', '14')";
if($conn->connect_error){echo $conn->connect_error;}
else{echo 'We can cnoonect DB';}

?> -->

<html lang="en">
<head>
<title>BHost</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="BHost template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="styles/bootstrap-4.1.2/bootstrap.min.css">
<link href="plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="plugins/OwlCarousel2-2.2.1/owl.carousel.css">
<link rel="stylesheet" type="text/css" href="plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
<link rel="stylesheet" type="text/css" href="plugins/OwlCarousel2-2.2.1/animate.css">
<link rel="stylesheet" type="text/css" href="styles/main_styles.css">
<link rel="stylesheet" type="text/css" href="styles/responsive.css">
<link rel="stylesheet" type="text/css" href="styles/contact.css">
<link rel="stylesheet" type="text/css" href="styles/contact_responsive.css">
</head>
<body>

<div class="super_container">
	
	<!-- Header -->

	<header class="header trans_400">
		<div class="header_content d-flex flex-row align-items-center justify-content-start trans_400">
			<div class="logo"><a href="index.phtml"><span>b</span>Host</a></div>
			<div class="container">
				<div class="row">
					<div class="col-lg-10 offset-lg-2">
						<nav class="main_nav">
							<ul class="d-flex flex-row align-items-center justify-content-start">
								<li class="active"><a href="index.phtml">Home</a></li>
								<li><a href="about.html">About us</a></li>
								<li><a href="services.html">Services</a></li>
								<li><a href="blog.html">News</a></li>
								<li><a href="contact.html">Contact</a></li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
			<div class="header_right d-flex flex-row align-items-center justify-content-start">

				<!-- Header Links -->
				<div class="header_links">
					<ul class="d-flex flex-row align-items-center justify-content-start">
						<li><a href="#">Webmail</a></li>
						<li><a href="#">Chat</a></li>
						<li><a href="#">Login</a></li>
					</ul>
				</div>

				<!-- Phone -->
				<div class="phone d-flex flex-row align-items-center justify-content-start">
					<i class="fa fa-phone" aria-hidden="true"></i>
					<div>652-345 3222 11</div>
				</div>

				<!-- Hamburger -->
				<div class="hamburger"><i class="fa fa-bars" aria-hidden="true"></i></div>
			</div>	
		</div>
	</header>

	<!-- Menu -->

	<div class="menu trans_500">
		<div class="menu_content d-flex flex-column align-items-center justify-content-center">
			<div class="menu_nav trans_500">
				<ul class="text-center">
					<li><a href="index.phtml">Home</a></li>
					<li><a href="about.html">About us</a></li>
					<li><a href="services.html">Services</a></li>
					<li><a href="blog.html">News</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</div>
			<div class="phone menu_phone d-flex flex-row align-items-center justify-content-start">
				<i class="fa fa-phone" aria-hidden="true"></i>
				<div>652-345 3222 11</div>
			</div>
		</div>
	</div>

	<!-- Home -->

	<div class="home">
		<!-- <div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="images/h.jpg" data-speed="0.8"></div> -->
		<!-- <div class="home_container"> -->
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="home_content text-center">
							<!-- <div class="home_icon ml-auto mr-auto d-flex flex-column align-items-center justify-content-center"><div><img src="images/icon_1.svg" alt="https://www.flaticon.com/authors/srip"></div></div> -->
							<div class="home_title">Search</div>
							<div class="domain_search">
								<form action="iot.phtml" method="post" class="domain_search_form" id="domain_search_form">
									<input type="text" class="domain_search_input" placeholder="Search.." required="required" name="key" id="key">
									<!-- <div class="domain_search_dropdown d-flex flex-row align-items-center justify-content-center">
										<div class="domain_search_selected">.com</div>
										<ul>
											<li>.com</li>
											<li>.io</li>
											<li>.net</li>
										</ul>
									</div> -->
									<input type="submit" name="submitted" value="Search" class="domain_search_button">
								</form>
								<?php
									while ($res = mysqli_fetch_array($result)){
										echo "<h1>".$res["data_id"]."</h1>";
										echo "<h1>".$res["weight"]."</h1>";
										echo "<h1>".$res["heigh"]."</h1>";

									}
								?>
							</div>
						</div>
					</div>
				</div>
			</div>
		<!-- </div> -->
	</div>

	<!-- Domain Pricing -->

	<!-- <div class="domain_pricing"> -->
		<div class="container" style="padding-top: 0">
			<div class="row">
				<div class="col">
					<div class="domain_pricing_content">
						<ul class="d-flex flex-md-row flex-column align-items-center justify-content-md-between justify-content-center">
							<li><a href="#">Recipe</a></li>
							<li><a href="#">Food Delivery</a></li>
							<li><a href="#">Work out</a></li>
							<li><a href="#">Fitness center</a></li>
							<li><a href="#">Analysis</a></li>
							<li><a href="#">IoT</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	<!-- </div> -->

	<!-- Why Choose Us -->

	<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

<div class="col-lg-8 contact_form_col">
					<div class="contact_form_container">
						<div class="contact_title">Get in touch</div>
						<form action="insert.php" method="post" class="contact_form" id="contact_form">
							<div class="row contact_row">
								<div class="col-lg-6"><input type="email" class="contact_input" id="data_id" name="data_id" placeholder="ID" required="required"></div>
								<div class="col-12"><input type="text" class="contact_input" id="weight" name="weight" placeholder="Weight" required="required"></div>
								<div class="col-lg-6"><input type="text" class="contact_input" id="heigh" name="heigh" placeholder="Heigh" required="required"></div>
								<div class="col-lg-6"><input type="text" class="contact_input" id="heigh" id="age" name="age" placeholder="Age" required="required"></div>
								<input type = "submit" value = "submit">
							</div>
							<!-- <button class="contact_button trans_200">send</button> -->
						</form>
					</div>
				</div>

	
	<!-- <form action ="insert.php" method = "post">
	<input type="text" id="data_id" name="data_id" placeholder="ID" required="required">
	<br>
	<input type="text" id="weight" name="weight" placeholder="Weight" required="required">
	<br>
	<input type="text" id="heigh" name="heigh" placeholder="Heigh" required="required">
	<br>
	<input type="text" id="age" name="age" placeholder="Age" required="required">
	<br>
	<input type = "submit" value = "submit"> -->


</form>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
	</footer>
</div>
<div>
	<?php 

		$sql = "SELECT * FROM customer";
		$result = $conn->query($sql);

		if ($result->num_rows > 0) {
		    // output data of each row
		    while($row = $result->fetch_assoc()) {
		        echo "id: " . $row["customer_id"] . "name: " . $row["customer_fname"]. "<br>";
		    }
		} else {
		    echo "0 results";
		}
		$conn->close();

	?>
</div>

<script src="js/jquery-3.2.1.min.js"></script>
<script src="styles/bootstrap-4.1.2/popper.js"></script>
<script src="styles/bootstrap-4.1.2/bootstrap.min.js"></script>
<script src="plugins/greensock/TweenMax.min.js"></script>
<script src="plugins/greensock/TimelineMax.min.js"></script>
<script src="plugins/scrollmagic/ScrollMagic.min.js"></script>
<script src="plugins/greensock/animation.gsap.min.js"></script>
<script src="plugins/greensock/ScrollToPlugin.min.js"></script>
<script src="plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
<script src="plugins/easing/easing.js"></script>
<script src="plugins/progressbar/progressbar.min.js"></script>
<script src="plugins/parallax-js-master/parallax.min.js"></script>
<script src="js/custom.js"></script>
</body>
</html>